### ISSUE TITLE
stage does not resize

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#30]
on my 13" screen, the right-hand edge of the stage and tool palette are hanging off to the right, and resizing the window doesn't change this. the stage needs to adjust/scale to the proportions of the browser window (it has always done this in UpStage). i think the bottom may also be cut off.
i'm trying to upload a screenshot but it's not working ... 
![Uploading Screenshot 2017-04-12.png…]()

**Comment by rohrlach** [comment]
@helen your screen shot doesn't appear to work can you try again?

**Comment by helenvarley** [comment]
![screenshot 2017-04-12](https://cloud.githubusercontent.com/assets/3437324/24975072/b96247de-1fc4-11e7-937f-800d26cc55e1.png)

**Comment by rohrlach** [comment]
@helenvarley This may have been fixed due to resolution of #6 please retest

**Comment by helenvarley** [comment]
it's better; but i'm still getting scrollbars, & the bottom of the chat window is below the bottom of the browser window. (using firefox on 13" mac)
![screen shot 2017-04-17 at 4 37 55 pm](https://cloud.githubusercontent.com/assets/3437324/25092076/63ed7d84-238c-11e7-9320-0af77e11a73b.png)

**Comment by helenvarley** [comment]
on my new ubuntu 14" laptop i'm also seeing scrollbars, both at the side and the bottom.

**Comment by rohrlach** [comment]
Okay, so:

- Working fine on WebKit based browsers
- Needs addressing on Gecko based browsers

Not sure if anyone has the capacity to test on Trident or Edge?

**Comment by helenvarley** [comment]
er ... what browsers are those? most important is that it works well on firefox, chrome, safari & any other that has a major presence (does IE still get used much? most windows users i know are using firefox or chrome)

**Comment by rohrlach** [comment]
WebKit powers Safari
Blink powers Chrome and Opera (Blink is a fork of WebKit)
Gecko powers Firefox
Trident powers Internet Explorer
Edge powers well... Edge

**Comment by helenvarley** [comment]
ok; the students are probably able to test on IE. could we assign that to them? & do we need to worry about Edge? we do want to be as accessible as possible, but at the same time we have to be realistic about what we can achieve.

**Comment by rohrlach** [comment]
It should be easier to be compatible with Edge than IE . (Edge is the IE replacement as of Windows 10)

I'll assign this to them in the next sprint

**Comment by rohrlach** [comment]
Superseded
